-- MySQL Script generated by MySQL Workbench
-- Σαβ 29 Ιούλ 2017 04:14:48 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bnb_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bnb_db` ;

-- -----------------------------------------------------
-- Schema bnb_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bnb_db` DEFAULT CHARACTER SET utf8 ;
USE `bnb_db` ;

-- -----------------------------------------------------
-- Table `bnb_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`user` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `passhash` VARCHAR(128) NOT NULL,
  `first_name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `is_verified` TINYINT NOT NULL,
  `is_host` TINYINT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_num` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`location` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `street_no` SMALLINT(1) NOT NULL,
  `house_no` SMALLINT(1) NULL,
  `city` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NULL,
  `postal_code` VARCHAR(20) NULL,
  `latitude` REAL NOT NULL,
  `longtitude` REAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`listings` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`listings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `listing_url` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `summary` VARCHAR(200) NOT NULL,
  `owner_id` INT NOT NULL,
  `capacity` VARCHAR(45) NOT NULL,
  `rooms_no` TINYINT NOT NULL,
  `bathrooms_no` DECIMAL NOT NULL,
  `min_nights` SMALLINT(1) NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_listings_location1_idx` (`location_id` ASC),
  CONSTRAINT `owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `bnb_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_listings_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `bnb_db`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`calendar` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`calendar` (
  `listings_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `available` TINYINT NOT NULL,
  `price` VARCHAR(45) NULL,
  `guest_id` INT NULL,
  PRIMARY KEY (`listings_id`, `date`),
  INDEX `fk_calendar_user1_idx` (`guest_id` ASC),
  CONSTRAINT `fk_calendar_listings1`
    FOREIGN KEY (`listings_id`)
    REFERENCES `bnb_db`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_user1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `bnb_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`reviews` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`reviews` (
  `listings_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `reviewer_id` INT NOT NULL,
  `reviewer_name` VARCHAR(45) NOT NULL,
  `summary` VARCHAR(500) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_reviews_listings_idx` (`listings_id` ASC),
  INDEX `fk_reviews_reviewer_idx` (`reviewer_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_reviews_listings`
    FOREIGN KEY (`listings_id`)
    REFERENCES `bnb_db`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_reviewer`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `bnb_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`bed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`bed` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`bed` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bedroom_no` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `is_common` TINYINT NOT NULL,
  `listings_id` INT NOT NULL,
  INDEX `fk_bed_listings1_idx` (`listings_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bed_listings1`
    FOREIGN KEY (`listings_id`)
    REFERENCES `bnb_db`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`amenities` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`amenities` (
  `essentials` TINYINT NOT NULL,
  `wifi` TINYINT NOT NULL,
  `shampoo` TINYINT NOT NULL,
  `closet_drawers` TINYINT NOT NULL,
  `tv` TINYINT NOT NULL,
  `heat` TINYINT NOT NULL,
  `air_conditioning` TINYINT NOT NULL,
  `breakfast_coffee_tea` TINYINT NOT NULL,
  `office_wspace` TINYINT NOT NULL,
  `fireplace` TINYINT NOT NULL,
  `iron` TINYINT NOT NULL,
  `hairdryer` TINYINT NOT NULL,
  `priv_entrance` TINYINT NOT NULL,
  `pets` TINYINT NOT NULL,
  `smoke_detector` TINYINT NOT NULL,
  `co_detector` TINYINT NOT NULL,
  `first_aids` TINYINT NOT NULL,
  `safety_card` TINYINT NOT NULL,
  `extinguisher` TINYINT NOT NULL,
  `bed_lock` TINYINT NOT NULL,
  `events` TINYINT NOT NULL,
  `smoking` TINYINT NOT NULL,
  `listings_id` INT NOT NULL,
  PRIMARY KEY (`listings_id`),
  INDEX `fk_amenities_listings1_idx` (`listings_id` ASC),
  CONSTRAINT `fk_amenities_listings1`
    FOREIGN KEY (`listings_id`)
    REFERENCES `bnb_db`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`usable_spaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`usable_spaces` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`usable_spaces` (
  `priv_living_room` TINYINT NOT NULL,
  `pool` TINYINT NOT NULL,
  `kitchen` TINYINT NOT NULL,
  `laundry_washer` TINYINT NOT NULL,
  `laundry_dryer` TINYINT NOT NULL,
  `parking` TINYINT NOT NULL,
  `elevator` TINYINT NOT NULL,
  `jacuzzi` TINYINT NOT NULL,
  `gym` TINYINT NOT NULL,
  `listings_id` INT NOT NULL,
  PRIMARY KEY (`listings_id`),
  INDEX `fk_usable_spaces_listings1_idx` (`listings_id` ASC),
  CONSTRAINT `fk_usable_spaces_listings1`
    FOREIGN KEY (`listings_id`)
    REFERENCES `bnb_db`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bnb_db`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bnb_db`.`admin` ;

CREATE TABLE IF NOT EXISTS `bnb_db`.`admin` (
  `username` VARCHAR(20) NOT NULL,
  `passhash` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bnb_db`.`admin`
-- -----------------------------------------------------
START TRANSACTION;
USE `bnb_db`;
INSERT INTO `bnb_db`.`admin` (`username`, `passhash`) VALUES ('admin', 'c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec');

COMMIT;

